#!/usr/bin/env python3
import zipfile, os

OUT = r"D:/OJAN/File BSI Fauzan/Semester 4/Tugas Kuliah/KopkarRSUI/Dokumentasi_Lengkap_KopkarRSUI.docx"

def esc(t):
    return t.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

def para(text, bold=False, size=22, bullet=False, mono=False):
    b = "<w:b/>" if bold else ""
    font = '<w:rFonts w:ascii="Courier New" w:hAnsi="Courier New"/>' if mono else ""
    ind = '<w:ind w:left="360"/>' if bullet else ""
    ppr = f"<w:pPr>{ind}</w:pPr>" if ind else ""
    sz = 18 if mono else size
    return (f"<w:p>{ppr}<w:r><w:rPr>{font}{b}<w:sz w:val='{sz}'/></w:rPr>"
            f"<w:t xml:space='preserve'>{esc(text)}</w:t></w:r></w:p>")

def render():
    body = []
    for style, text in CONTENT:
        if style == "h1": body.append(para(text, bold=True, size=32))
        elif style == "h2": body.append(para(text, bold=True, size=26))
        elif style == "h3": body.append(para(text, bold=True, size=24))
        elif style == "b": body.append(para("\u2022 " + text, size=22, bullet=True))
        elif style == "m": body.append(para(text, mono=True))
        else: body.append(para(text, size=22))
    return ('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            '<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
            f"<w:body>{''.join(body)}</w:body></w:document>")

CONTENT = [
    ("h1", "Dokumentasi Lengkap \u2014 Aplikasi KopkarRSUI"),
    ("p", "Aplikasi Koperasi Karyawan RSUI (Koperasi Rumah Sakit UI)"),
    ("p", "Platform: Android (min SDK 24, target SDK 34)"),
    ("p", "Stack: Kotlin, Jetpack Compose (Material 3), Hilt (DI), Room (SQLite), Clean Architecture"),
    ("p", "Lokasi: D:\\OJAN\\File BSI Fauzan\\Semester 4\\Tugas Kuliah\\KopkarRSUI"),
    ("p", "Versi: 1.0.0  |  Dokumentasi: 30 September 2026"),
    ("h2", "1.  Ringkasan Aplikasi"),
    ("p", "KopkarRSUI adalah aplikasi Android untuk pengelolaan koperasi karyawan RS UI. Mendukung tiga jenis pengguna: anggota biasa, pengurus koperasi (ketua, bendahara, sekretaris, PJ keanggotaan), dan admin. Akses fitur berbeda berdasarkan record admin di database."),
    ("p", "Fitur utama: autentikasi PIN SHA-256, dashboard anggota, simpanan (pokok/wajib/sukarela), transaksi & poin, SHU, manajemen anggota, panel pengurus dengan audit trail dan backup, serta informasi RAT."),
    ("p", "Data lokal via Room (SQLite). Seed: 3 anggota demo (KPR-001 s.d. KPR-003, PIN 123456), 1 pengurus (KPR-001 = Ketua)."),
    ("h2", "2.  Arsitektur"),
    ("b", "domain/ \u2014 Interface repository + use case (7 file, 145 baris)"),
    ("b", "data/ \u2014 Entity Room, DAO, repository impl, database (26 file, 1.293 baris)"),
    ("b", "presentation/ \u2014 Screen Compose, ViewModel, komponen (25 file, 4.571 baris)"),
    ("b", "di/ \u2014 Module Hilt (2 file)"),
    ("b", "ui/theme/ \u2014 Palet Kopkar, TextSize, Material 3 theme"),
    ("b", "util/ \u2014 FormatUtils, NotificationHelper, PasswordUtils (SHA-256), ExportHelper"),
    ("h2", "3.  Fitur Detail"),
    ("h3", "3.1  Autentikasi & Login"),
    ("p", "Layar awal aplikasi (start destination). Bottom nav disembunyikan agar fitur lain tidak bisa diakses sebelum login."),
    ("b", "Input: Nomor Anggota + PIN 6 digit."),
    ("b", "Verifikasi: PIN di-hash SHA-256 lalu dibandingkan dengan pin_hash di tabel members. Plain text tidak pernah disimpan."),
    ("b", "Validasi status: hanya anggota 'aktif' yang bisa login."),
    ("b", "Role routing: cek tabel admins \u2014 ada record admin aktif \u2192 AdminDashboard; tidak ada \u2192 Dashboard anggota."),
    ("b", "Sesi: sessionManager.saveSession(memberId) disimpan di SharedPreferences."),
    ("b", "Notifikasi sambutan via NotificationHelper setelah login sukses."),
    ("b", "Placeholder: Biometrik, Lupa PIN, Daftar (UI placeholder)."),
    ("b", "Error: pesan spesifik per kasus (nomor tidak ditemukan, akun tidak aktif, PIN salah, field kosong)."),
    ("h3", "3.2  Dashboard Anggota"),
    ("p", "Layar utama setelah login anggota."),
    ("b", "Header: sapaan 'Selamat datang, [nama]', nomor anggota, ikon dompet."),
    ("b", "4 Stat cards: Total Tabungan, Total Poin, SHU Tahun Ini, Anggota Aktif."),
    ("b", "Transaksi Terbaru: daftar dengan ikon tipe, keterangan, jumlah (+/- warna hijau/merah)."),
    ("b", "Manajemen Anggota: pencarian, tombol navigasi, daftar anggota (avatar, nama, no anggota, jabatan, status, tabungan/pinjaman, tanggal gabung)."),
    ("b", "Loading overlay + error state dengan tombol 'Coba Lagi'."),
    ("b", "Data: parallel Flow dari 5 repository via DashboardViewModel."),
    ("h3", "3.3  Tabungan & Pinjaman"),
    ("p", "Dua tab utama dengan sub-tab detail."),
    ("b", "Tab Simpanan: sub-tab Pokok, Wajib, Sukarela, Riwayat, Laporan. Header total saldo."),
    ("b", "Tab Pinjaman: Konsumtif (maks Rp 10jt, 12 bln, 5%), Produktif (maks Rp 25jt, 24 bln, 6%), Darurat (maks Rp 5jt, 6 bln, 3%)."),
    ("b", "Data: SavingsViewModel dari SavingsAccount per jenis + riwayat transaksi."),
    ("h3", "3.4  Transaksi & Poin"),
    ("b", "Header: total poin kumulatif."),
    ("b", "Filter chips: Semua / Setoran / Penarikan / Belanja."),
    ("b", "Item: ikon tipe, keterangan, tanggal, jumlah (hijau/merah), poin (badge oranye)."),
    ("b", "Detail transaksi: layar terpisah untuk info lengkap satu transaksi."),
    ("h3", "3.5  SHU (Sisa Hasil Usaha)"),
    ("p", "5 tab perhitungan dan distribusi SHU tahunan:"),
    ("b", "Perhitungan: Laba Bersih \u2192 Cadangan 18% \u2192 SHU Total \u2192 SHU Bersih ke Anggota."),
    ("b", "Distribusi: rincian per anggota (nama, porsi, jumlah)."),
    ("b", "Riwayat: histori SHU tahun sebelumnya."),
    ("b", "Laporan: modal sendiri, total aset, SHU per anggota rata-rata."),
    ("b", "Transparansi: informasi distribusi untuk anggota."),
    ("h3", "3.6  Profil & Logout"),
    ("b", "Header: nama, no anggota, status keanggotaan."),
    ("b", "Akun & Keamanan: Ubah PIN (placeholder), Biometrik (status)."),
    ("b", "Informasi: Data Diri, Syarat & Ketentuan, Tentang Aplikasi."),
    ("b", "Logout: tombol merah \u2192 dialog konfirmasi \u2192 clearSession() \u2192 navigate(AuthLogin) popUpTo(0)."),
    ("b", "Bottom nav tampil di Profil, tidak tampil di login."),
    ("h3", "3.7  Manajemen Anggota"),
    ("p", "Diakses dari tombol di Dashboard. 5 section:"),
    ("b", "Pendaftaran: form (no anggota, nama, NIK, no HP, email, alamat, jabatan, PIN) + konfirmasi."),
    ("b", "Profil Anggota: pencarian \u2192 detail lengkap + aksi (placeholder)."),
    ("b", "Kartu Digital: pilih anggota \u2192 kartu anggota + QR + Bagikan/Unduh (placeholder)."),
    ("b", "Status Keanggotaan: filter + ringkasan + daftar per status."),
    ("b", "Data Suplier: pencarian, daftar, detail, tambah (dialog placeholder)."),
    ("h3", "3.8  Panel Admin / Pengurus"),
    ("p", "Untuk pengurus dengan record admin aktif."),
    ("b", "Stat cards + aksi cepat (Audit Trail, Backup, Restore)."),
    ("b", "Aktivitas Terakhir: log aktivitas terbaru."),
    ("b", "Logout ikon di header \u2192 clearSession \u2192 login."),
    ("b", "Bottom nav tetap tampil \u2014 pengurus bisa akses fitur anggota."),
    ("h3", "3.9  Audit Trail"),
    ("b", "Log: nama tabel, aksi, timestamp, oldValue, newValue."),
    ("b", "Saat ini menampilkan data sample (AuditLogger belum diimplementasi ulang)."),
    ("h3", "3.10  Backup & Restore"),
    ("b", "Buat Backup: salin database ke file backup."),
    ("b", "Daftar Backup: nama, tanggal, ukuran KB."),
    ("b", "Aksi per file: Restore + Hapus (dialog konfirmasi)."),
    ("h3", "3.11  RAT (Rapat Anggota Tahunan)"),
    ("b", "3 tab: Berita Acara (ringkasan + agenda), Voting (hasil kandidat), Rekomendasi."),
    ("b", "Catatan: route 'rat' belum ada akses dari UI lain (dead route)."),
    ("h2", "4.  User Flow"),
    ("p", "Diagram alur dalam bentuk skema teks monospace (Courier New)."),
    ("h3", "4.1  Alur Login"),
    ("m", "+========================+"),
    ("m", "|    APLIKASI DIBUKA     |"),
    ("m", "+========================+"),
    ("m", "         |"),
    ("m", "         v"),
    ("m", "+========================+"),
    ("m", "|    LOGIN SCREEN        |  <-- startDestination"),
    ("m", "|    (navbar hidden)     |      bottom nav tidak tampil"),
    ("m", "+========================+"),
    ("m", "         |"),
    ("m", "         |  user isi: No Anggota + PIN (6 digit)"),
    ("m", "         v"),
    ("m", "+========================+"),
    ("m", "|  LoginViewModel        |"),
    ("m", "|  .login(nAnggota,pin)  |"),
    ("m", "+========================+"),
    ("m", "         |"),
    ("m", "         |  SHA-256 hash compare"),
    ("m", "         v"),
    ("m", "     {PIN Benar?}"),
    ("m", "      /        \\"),
    ("m", "   Tidak       Ya"),
    ("m", "    |           |"),
    ("m", "    v           v"),
    ("m", " [Error:   [Query Admin record"),
    ("m", "  'PIN      via AdminDao]"),
    ("m", "  salah'       |"),
    ("m", "    |     {Admin Aktif?}"),
    ("m", "    |      /         \\"),
    ("m", "    |    Ya         Tidak"),
    ("m", "    |     |           |"),
    ("m", "    v     v           v"),
    ("m", " [Kembali +=========+ +===========+"),
    ("m", "  ke form]|  ADMIN  | | DASHBOARD |"),
    ("m", "         |DASHBOARD| |  ANGGOTA  |"),
    ("m", "         |(panel   | | (stat,    |"),
    ("m", "         |pengurus)| | transaksi,|"),
    ("m", "         +=========+ | nav aktif)|"),
    ("m", "                     +===========+"),
    ("m", ""),
    ("m", "  Session: sessionManager.saveSession(memberId)"),
    ("m", "  Notifikasi sambutan ditampilkan."),
    ("h3", "4.2  Alur Logout"),
    ("m", "+========================+"),
    ("m", "|    PROFIL SCREEN       |"),
    ("m", "|    (tab Profil)        |"),
    ("m", "+========================+"),
    ("m", "         |"),
    ("m", "         |  klik tombol merah 'Keluar'"),
    ("m", "         v"),
    ("m", "+========================+"),
    ("m", "|    DIALOG KONFIRMASI   |"),
    ("m", "|  'Keluar dari akun?    |"),
    ("m", "|   Anda akan kembali    |"),
    ("m", "|   ke halaman login'    |"),
    ("m", "+========================+"),
    ("m", "      /          \\"),
    ("m", "   Batal       'Keluar'"),
    ("m", "     |            |"),
    ("m", "     v            v"),
    ("m", " [Tutup      [clearSession()]"),
    ("m", "  dialog]     [SharedPreferences |"),
    ("m", "               di-clear]         |"),
    ("m", "                  |              |"),
    ("m", "                  v              |"),
    ("m", "      [navigate(AuthLogin)]      |"),
    ("m", "       popUpTo(0) inclusive      |"),
    ("m", "       (back stack bersih)       |"),
    ("m", "                  |              |"),
    ("m", "                  v              |"),
    ("m", "      +========================+ |"),
    ("m", "      |    LOGIN SCREEN        |<+"),
    ("m", "      |    (navbar hidden)     |"),
    ("m", "      +========================+"),
    ("m", ""),
    ("m", "  Admin juga bisa logout dari ikon di"),
    ("m", "  header AdminDashboard \u2014 alur sama."),
    ("h3", "4.3  Alur Navigasi (Bottom Nav)"),
    ("m", "  Bottom nav tampil di SEMUA route KECUALI auth/login."),
    ("m", "  5 tab utama:"),
    ("m", ""),
    ("m", "  [Beranda] [Tabungan] [Transaksi] [SHU] [Profil]"),
    ("m", "     |          |           |         |       |"),
    ("m", "     v          v           v         v       v"),
    ("m", " Dashboard  Savings   Transaction   SHU   Profile"),
    ("m", " Screen     Screen      Screen     Screen Screen"),
    ("m", ""),
    ("m", "  Mekanisme: popUpTo(findStartDestination) + saveState + restoreState"),
    ("m", "  + launchSingleTop. State tiap tab dipertahankan."),
    ("m", ""),
    ("m", "  Layar TIDAK diakses dari bottom nav:"),
    ("m", "  - AdminDashboard (dari login role routing)"),
    ("m", "  - AuditLog, BackupRestore (dari AdminDashboard)"),
    ("m", "  - MemberManagement (dari tombol di Dashboard)"),
    ("m", "  - RAT (dead route, belum ada akses)"),
    ("h3", "4.4  Alur Tabungan"),
    ("m", "  [Dashboard] -- klik 'Tabungan' --> [SavingsScreen]"),
    ("m", "                                           |"),
    ("m", "                    +=====================+=====================+"),
    ("m", "                    |                                          |"),
    ("m", "                    v                                          v"),
    ("m", "          +---------------------+      +---------------------+"),
    ("m", "          |  TAB 'Simpanan'     |      |  TAB 'Pinjaman'     |"),
    ("m", "          +---------------------+      +---------------------+"),
    ("m", "                    |                                          |"),
    ("m", "          +---------+--------+      +----------+----------+"),
    ("m", "          |    |    |    |   |      |          |          |"),
    ("m", "          v    v    v    v   v      v          v          v"),
    ("m", "        Pokok Wajib Sukarela Riwayat Konsumtif Produktif Darurat"),
    ("m", "                          Laporan  (Rp10jt)  (Rp25jt)  (Rp5jt)"),
    ("m", "                                   12bln 5%  24bln 6%  6bln 3%"),
    ("h3", "4.5  Alur Manajemen Anggota"),
    ("m", "  [Dashboard] -- tombol 'Manajemen Anggota' --> [MemberManagementScreen]"),
    ("m", "                                                       |"),
    ("m", "          +----------+----------+----------+----------+----------+"),
    ("m", "          |          |          |          |          |          |"),
    ("m", "          v          v          v          v          v          v"),
    ("m", "       Pendaftaran  Profil   Kartu     Status    Data"),
    ("m", "       Anggota Baru Anggota  Digital   Keangg.  Suplier"),
    ("m", "          |          |          |          |          |"),
    ("m", "          v          v          v          v          v"),
    ("m", "       Form input  Search &  Pilih      Filter &  Search &"),
    ("m", "       + konfirmasi detail   anggota   ringkasan  detail"),
    ("m", "          |          |          |          |          |"),
    ("m", "          v          v          v          v          v"),
    ("m", "       Dialog      Detail +   Kartu      Daftar     Detail +"),
    ("m", "       sukses      aksi       anggota    per status tambah"),
    ("h3", "4.6  Alur Panel Admin"),
    ("m", "  [Login sebagai pengurus]"),
    ("m", "         |"),
    ("m", "         v"),
    ("m", "  +========================+"),
    ("m", "  |    ADMIN DASHBOARD     |"),
    ("m", "  |    (panel pengurus)    |"),
    ("m", "  +========================+"),
    ("m", "    |        |        |      |"),
    ("m", "    v        v        v      v"),
    ("m", " Stat     Audit    Backup  Logout"),
    ("m", " cards    Trail    DB      (ikon)"),
    ("m", "    |        |        |      |"),
    ("m", "    v        v        v      |"),
    ("m", "    |   [AuditLog] [Backup]  |"),
    ("m", "    |    Screen   Restore    |"),
    ("m", "    |              Screen    |"),
    ("m", "    |                 |      |"),
    ("m", "    |          [Buat/Restore/ |"),
    ("m", "    |           Hapus Backup] |"),
    ("m", "    v                 v      v"),
    ("m", "  [Bottom nav tetap tampil \u2014 pengurus akses fitur anggota]"),
    ("h2", "5.  Skema Database (Ringkas)"),
    ("p", "8 tabel utama Room database:"),
    ("b", "members \u2014 id, no_anggota (unique), nama, nik, no_hp, email, alamat, tgl_gabung, status, pin_hash, biometric_enabled."),
    ("b", "admins \u2014 id, member_id (FK unique), role (ketua/bendahara/sekretaris/pj_keanggotaan), izin_json, aktif_sejak, status."),
    ("b", "savings_accounts \u2014 id, member_id (FK), jenis (pokok/wajib/sukarela), saldo, status."),
    ("b", "transactions \u2014 id, member_id (FK), tipe (setoran/penarikan/belanja), jumlah, keterangan, poin_dihasilkan, created_at."),
    ("b", "point_ledger \u2014 id, member_id (FK), poin, tipe, keterangan, created_at."),
    ("b", "shu_allocations \u2014 id, member_id (FK), tahun, jumlah, persentase, status."),
    ("b", "financial_statements \u2014 id, tahun, jenis, jumlah, keterangan, status."),
    ("b", "audit_logs \u2014 id, table_name, action, old_value, new_value, timestamp."),
    ("h2", "6.  Akun Demo & Install"),
    ("m", "  +-------------+--------+------------------+----------------+"),
    ("m", "  | No Anggota  |  PIN   | Nama             | Role           |"),
    ("m", "  +-------------+--------+------------------+----------------+"),
    ("m", "  | KPR-001     | 123456 | Budi Santoso     | Ketua (admin)  |"),
    ("m", "  | KPR-002     | 123456 | Siti Rahayu      | Anggota        |"),
    ("m", "  | KPR-003     | 123456 | Ahmad Fauzi      | Anggota        |"),
    ("m", "  +-------------+--------+------------------+----------------+"),
    ("p", "Catatan: seed hanya jalan saat database baru. Ubah seed \u2192 jalankan adb shell pm clear com.example.kopkarrsui dulu."),
    ("m", "  adb install -r app/build/outputs/apk/debug/app-debug.apk"),
    ("m", "  adb shell monkey -p com.example.kopkarrsui -c android.intent.category.LAUNCHER 1"),
    ("h2", "7.  Kompresi Kode (Ringkas)"),
    ("p", "Detail lengkap: Dokumentasi_Kompresi_Kode.docx."),
    ("b", "formatRupiah: 3 implementasi \u2192 1 util (FormatUtils.kt)."),
    ("b", "Dead code dihapus: AuditLogger.kt, tombol mati DashboardScreen, showMemberList."),
    ("b", "Warna: 176 hex \u2192 palet Kopkar (KopkarGreen/Red/Blue/Orange/Purple/Teal/Gray/Yellow) di Color.kt."),
    ("b", "Teks: 320 literal sp \u2192 TextSize (s10 s.d. s28) di TextSize.kt."),
    ("b", "Hasil: 70 file, 6.596 baris (dari +/- 6.900), build sukses."),
    ("h2", "8.  Daftar File Utama"),
    ("m", "  app/src/main/java/com/example/kopkarrsui/"),
    ("m", "  +-- MainActivity.kt              (entry, nav bar conditional)"),
    ("m", "  +-- KopkarApplication.kt         (Hilt application)"),
    ("m", "  +-- data/local/"),
    ("m", "  |   +-- KopkarDatabase.kt        (Room DB + seed)"),
    ("m", "  |   +-- SessionManager.kt        (SharedPreferences session)"),
    ("m", "  |   +-- DatabaseBackup.kt        (backup/restore SQLite)"),
    ("m", "  |   +-- dao/ (8 DAO)             (Member, Admin, Savings, Transaction, Point, SHU, Financial, AuditLog)"),
    ("m", "  |   +-- entity/ (8 entity)       (Member, Admin, SavingsAccount, Transaction, PointLedger, SHUAllocation, FinancialStatement, AuditLog)"),
    ("m", "  +-- data/repository/ (6 impl)    (pass-through ke DAO)"),
    ("m", "  +-- domain/repository/ (6)       (interface)"),
    ("m", "  +-- domain/usecase/ (1)          (MemberUseCase)"),
    ("m", "  +-- di/ (2 module)               (DatabaseModule, RepositoryModule)"),
    ("m", "  +-- presentation/"),
    ("m", "  |   +-- navigation/AppNavHost.kt (semua route + role routing)"),
    ("m", "  |   +-- component/"),
    ("m", "  |   |   +-- BottomNavBar.kt      (nav bar 5 tab + top app bar)"),
    ("m", "  |   |   +-- CommonComponents.kt  (StatCard, InfoCard, EmptyState, LoadingOverlay, ErrorState)"),
    ("m", "  |   +-- viewmodel/ (6 VM)        (Login, Dashboard, Savings, Transaction, SHU, Member)"),
    ("m", "  |   +-- screen/"),
    ("m", "  |       +-- auth/LoginScreen.kt"),
    ("m", "  |       +-- dashboard/DashboardScreen.kt + MemberManagementScreen.kt"),
    ("m", "  |       +-- savings/SavingsScreen.kt + SavingsTabContent.kt + SavingsComponents.kt"),
    ("m", "  |       +-- transaction/TransactionScreen.kt + TransactionDetailScreen.kt"),
    ("m", "  |       +-- shu/SHUScreen.kt + SHUTabContent.kt"),
    ("m", "  |       +-- profile/ProfileScreen.kt"),
    ("m", "  |       +-- admin/AdminDashboardScreen.kt + AuditLogScreen.kt + BackupRestoreScreen.kt"),
    ("m", "  |       +-- rat/RATScreen.kt (dead route)"),
    ("m", "  +-- ui/theme/Color.kt + TextSize.kt + Theme.kt + Type.kt"),
    ("m", "  +-- util/FormatUtils.kt + NotificationHelper.kt + PasswordUtils.kt + ExportHelper.kt"),
]

content_types = ('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
    '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
    '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
    '<Default Extension="xml" ContentType="application/xml"/>'
    '<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>'
    '</Types>')

rels = ('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
    '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
    '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>'
    '</Relationships>')

with zipfile.ZipFile(OUT, "w", zipfile.ZIP_DEFLATED) as z:
    z.writestr("[Content_Types].xml", content_types)
    z.writestr("_rels/.rels", rels)
    z.writestr("word/document.xml", render())

print("OK:", OUT, os.path.getsize(OUT), "bytes,", len(CONTENT), "items")
